### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by CorreyL**
Hello @alekseyzimin 

I've made various changes to the `README.md` file, encapsulating each change within a separate commit so you can easily discern the changes I've made. They mainly involved using sub-headers and putting things in code blocks where appropriate.

In the interest of full transparency, this edit is for an assignment for a university technical writing course. A higher grade will be rewarded if PRs are approved. Please let me know if there are any issues with this PR that could be rectified, or any further additions I can make, in order to achieve an approval.

### CODE REVIEW

**Comment by CorreyL** [comment]
Pinging this PR in hopes to make any necessary changes for an approval, as this assignment is due tonight.

**Comment by answer19831020** [comment]
you had wrote the following
 #set this to 1 for all Illumina-only assemblies

#set this to 1 if you have less than 20x long reads (454, Sanger, Pacbio) and less than 50x CLONE coverage by Illumina, Sanger or 454 mate pairs

#otherwise keep at 0

USE_LINKING_MATES = 0

This puzzled me a lot, this mean you need to set USE_LINKING_MATES=1 at any situation, no matter what reads you have. Illumina PE and jump reads ? Illumina PE and jump reads, and PacBio or MinION reads? But in my opinion, only Illumina reads USE_LINKING_MATES =1, while you had Illumina reads,  PacBio or MinION reads, you need to set USE_LINKING_MATES =0, Is it right?

**Comment by alekseyzimin** [comment]
Thank you for your improvements,  I just got back from vacation and merged the pull request.

**Comment by alekseyzimin** [comment]
I meant 

"set this to 1 if you have less than 20x long reads (454, Sanger, Pacbio) for hybrid assemblies OR less than 50x CLONE coverage by Illumina, Sanger or 454 mate pairs for assemblies without long reads"

**Pull request merged**
